version: "3.7"

volumes:
  data:

services:
  web:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./web:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80
    depends_on:
      db:
        condition: service_healthy
  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8000:80"
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12.4-alpine
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ./database:/db
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
